### ISSUE TITLE
DEL closes connection and causes web interface to freeze

### ISSUE THREAD

**Issue by kr** [ha/doozerd#5]
See https://groups.google.com/d/topic/doozer/f02QXY4ASlY

**Comment by progrium** [comment]
It's not just the web interface. The response of deleting also returns err_code 127 and sends something weird over the wire because the next request will cause unexpected bytes to be on the buffer causing a parse error (specifically, something other than a 4 byte length is received). Let me see if I can get a packet trace.

**Comment by progrium** [comment]
I guess 127 is the default value of err_code? So that's not helpful. Here is a dump of the delete operation (with websocket reconnecting after for some reason -- instead of the page becoming unresponsive like before):
https://groups.google.com/group/doozer/attach/ee1e72b470617984/del_foo_with_web_interface.pcap.zip

**Comment by progrium** [comment]
Somehow this is intermittent because I've been letting doozerd run and now I'm not getting the same behavior as before.

**Comment by mreiferson** [comment]
see https://github.com/ha/doozerd/pull/25

**Comment by mreiferson** [comment]
@kr think this can be closed now as of ha/doozerd@cd7b918e8b1123209d1f1af79a8073b1e864add7

**Comment by kr** [comment]
Good call. Thanks.
