### ISSUE TITLE
current master compiled error with go r58.1 on Mac OS X Lion

### ISSUE THREAD

**Issue by imxiaobo** [ha/doozerd#7]
please see output in the gist below:

https://gist.github.com/1103961

**Comment by chrismoos** [comment]
This error is because you have an older version (ha/doozer release branch) installed, and the code in doozerd is expecting what is in the _master_ branch on doozer.

Right now goinstall uses the _release_ branch if it exists, and so when you try to compile its pulling down an older version of doozer.

If you can checkout ha/doozer locally and install it manually you should be okay. Too bad goinstall doesn't have the ability to specify the branch name...

**Comment by imxiaobo** [comment]
@chrismoos:
Thank you for your answer, but I'm still quite new to Go and its build system. What do you mean by saying " checkout ha/doozer locally and install it manually"? I did clone the official repo and run the all.sh script but it doesn't help. I guess I should checkout the source and put them inside the Go src/pkg/ dir, am I right?

**Comment by chrismoos** [comment]
Yeah you can clone ha/doozer and put it into $GOROOT/src/pkg/github.com/ha

Something like...

``` bash
goinstall -clean github.com/ha/doozer && rm -rf $GOROOT/pkg/darwin_amd64/doozer && rm -rf $GOROOT/src/pkg/github.com/ha/doozer

git clone https://github.com/ha/doozer && cd doozer && cp -R . $GOROOT/src/pkg/github.com/ha/doozer
```

Make sure you have $GOROOT set before running the above.

After you do that do clean.sh and then all.sh in doozerd. You should be good to go.

**Comment by imxiaobo** [comment]
@chrismoos:
Thanks for your quick reply, finally I've managed to get it compiled!

**Comment by hannestyden** [comment]
These tips also got doozerd to compile for me, also on OS X Lion. Thanks!

It all seems to work properly, though one of the tests fail: https://gist.github.com/1136378

**Comment by bmizerany** [comment]
This should be fixed with the latest Go weekly and ha/doozerd/master. Please reopen if problem persists.
